steps:
  - name: 'maven:3.8.6-eclipse-temurin-17'
    entrypoint: 'mvn'
    args: ['clean', 'package', '-DskipTests']
  - name: 'ubuntu'
    entrypoint: 'bash'
    args: ['-c', 'ls -l target']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/urlshortener/urlshortener-app', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/urlshortener/urlshortener-app']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'urlshortener-app'
      - '--image'
      - 'gcr.io/urlshortener/urlshortener-app'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
images:
  - 'gcr.io/url-shortener/urlshortener-app'